Changed to use multi-ghc-travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,4 +1,39 @@
-language: haskell
+env:
+  - GHCVER=7.6.1
+  - GHCVER=7.6.2
+  - GHCVER=7.6.3
+  - GHCVER=7.8.1
+  - GHCVER=head
+
 before_install:
-  - sudo apt-get update -qq
-  - sudo apt-get install -qq libgsl0-dev liblapack-dev
+  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+  - travis_retry sudo apt-get update
+  - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
+  - travis_retry sudo apt-get update -qq
+  - travis_retry sudo apt-get install -qq libgsl0-dev liblapack-dev
+  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
+
+install:
+  - cabal-1.18 update
+  - cabal-1.18 install --only-dependencies --enable-tests --enable-benchmarks
+
+script:
+  - cabal-1.18 configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+  - cabal-1.18 build   # this builds all libraries and executables (including tests/benchmarks)
+  - cabal-1.18 test
+  - cabal-1.18 check
+  - cabal-1.18 sdist   # tests that a source-distribution can be generated
+ 
+  # The following scriptlet checks that the resulting source distribution can be built & installed
+  - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
+    cd dist/;
+    if [ -f "$SRC_TGZ" ]; then
+       cabal-1.18 install "$SRC_TGZ";
+    else
+       echo "expected '$SRC_TGZ' not found";
+       exit 1;
+    fi
+ 
+matrix:
+  allow_failures:
+   - env: GHCVER=head
